services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning-platform-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    networks:
      - private
      - public
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - REDIS_URI=${REDIS_URI}
      - PORT=${PORT}
    profiles:
      - prod
    restart: unless-stopped

  app-dev:
      build:
        context: .
        dockerfile: Dockerfile.dev
      container_name: learning-platform-api-dev
      ports:
        - "3000:3000"
      depends_on:
        - db
        - cache
      networks:
        - private
        - public
      environment:
        - MONGODB_URI=${MONGODB_URI}
        - MONGODB_DB_NAME=${MONGODB_DB_NAME}
        - REDIS_URI=${REDIS_URI}
        - PORT=${PORT}
        - NODE_ENV=development
      volumes:
        - .:/app               # Mount host code
        - node_modules:/app/node_modules  # Preserve container modules
      profiles:
        - dev
      restart: unless-stopped

  # MongoDB service
  db:
    image: mongodb/mongodb-community-server:6.0.3-ubi8
    container_name: mongodb-instance
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - private
    profiles:
      - dev
      - prod
    restart: unless-stopped

  # Redis service
  cache:
    image: redis:7.4-rc2-alpine
    container_name: redis-instance
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - private
    profiles:
      - dev
      - prod
    restart: unless-stopped

  # RedisInsight service
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5555:5540"
    environment:
      - REDIS_HOST={redis}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      # TODO: should be change that
      - private
      # - public
    profiles:
      - dev
    restart: unless-stopped

volumes:
  mongodb_data:
    name: mongodb_data
    driver: local
  node_modules:

networks:
  public:
  private:
    internal: true
