- name: Setup Infrastructure
  hosts: all
  remote_user: vagrant
  become: true
  roles:
    - common
    - docker

- name:  Install Observability stack (targets)
  hosts: registry, backend, cache, database
  remote_user: vagrant
  become: true
  roles:
    - target

- name:  Install Observability stack (observer)
  hosts: monitoring
  remote_user: vagrant
  become: true
  roles:
    - observer

- name: Installation of registry
  hosts: registry
  remote_user: vagrant
  become: true
  roles:
    - registry

- name: Build and push Docker image on monitoring VM
  hosts: monitoring
  remote_user: vagrant
  become: true
  vars:
    registry_ip: "192.168.56.14"
    image_name: "learning-platform-api"
    image_tag: "latest"
    project_dir: "/home/vagrant/learning-platform-nosql"
  roles:
    - build_and_push

- name: Installation of databases
  hosts: database
  remote_user: vagrant
  become: true
  roles:
    - mongo

- name: Installation of cache
  hosts: cache
  remote_user: vagrant
  become: true
  roles:
    - redis

- name: Pull and run Docker image on backend
  hosts: backend
  remote_user: vagrant
  become: true
  vars:
    registry_ip: "192.168.56.14"
    image_name: "learning-platform-api"
    image_tag: "latest"
    container_name: "learning-platform-api"
  roles:
    - pull_and_run
