- name: Installation of databases
  hosts: database
  remote_user: vagrant
  become: true
  tasks:
    - import_tasks: common_install.yml
    - import_tasks: mongo_install.yml

- name: Installation of cache
  hosts: cache
  remote_user: vagrant
  become: true
  tasks:
    - import_tasks: common_install.yml
    - name: Ensure Redis is present
      apt:
        pkg: redis-server
        state: latest

    - name: Ensure Redis is started
      service:
        name: redis-server
        state: started
        enabled: yes

    - name: Ensure Redis Configuration
      template:
        src: redis.conf.j2
        dest: /etc/redis/redis.conf
        owner: root
        group: root
        mode: "0644"
      notify: Redis Restart
  handlers:
    - name: Redis Restart
      service:
        name: redis-server
        state: restarted

- name: Installation of backend
  hosts: backend
  remote_user: vagrant
  become: true
  vars:
    registry_ip: "192.168.56.14"
  tasks:
    - import_tasks: common_install.yml
    - import_tasks: docker_install.yml

    - name: Create Docker daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["{{ registry_ip }}:5000"]
          }
      notify: Restart Docker

    - name: Create or update /etc/hosts entry
      lineinfile:
        path: /etc/hosts
        line: "{{ registry_ip }} registry"
        state: present
  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted

- name: Installation of monitoring
  hosts: monitoring
  remote_user: vagrant
  tasks:
    - import_tasks: common_install.yml

- name: Installation of registry
  hosts: registry
  remote_user: vagrant
  become: true
  tasks:
    - import_tasks: common_install.yml
    - import_tasks: docker_install.yml

    - name: Create registry data directory
      ansible.builtin.file:
        path: /var/lib/registry
        state: directory
        mode: "0755"

    - name: Run Docker Registry
      community.docker.docker_container:
        name: registry
        image: registry:2
        ports:
          - "5000:5000"
        volumes:
          - /var/lib/registry:/var/lib/registry
        restart_policy: always
        env:
          REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
          REGISTRY_STORAGE_DELETE_ENABLED: "true"
